#!/bin/bash
# Generates supabase/seed.sql: the NYC subset of docs/private/places.sqlite as
# idempotent INSERTs into public.places (WKT for the geography column).
# Apply with: supabase db push --include-seed   (after supabase link)
set -euo pipefail
cd "$(dirname "$0")/.."

python3 - <<'PYEOF'
import sqlite3

# Five boroughs plus a sliver of NJ; matches the seed scope in roadmap item 4.
LAT = (40.49, 40.92)
LON = (-74.27, -73.68)
BATCH = 1000

db = sqlite3.connect('docs/private/places.sqlite')
rows = db.execute(
    'SELECT gers_id, name, lat, lon, category, subtype, confidence FROM places'
    ' WHERE lat BETWEEN ? AND ? AND lon BETWEEN ? AND ?',
    (*LAT, *LON),
).fetchall()

def lit(value):
    if value is None:
        return 'null'
    if isinstance(value, str):
        return "'" + value.replace("'", "''") + "'"
    return repr(value)

with open('supabase/seed.sql', 'w') as out:
    out.write('-- Generated by scripts/seed-places-nyc.sh — do not edit.\n')
    for start in range(0, len(rows), BATCH):
        out.write('insert into places (gers_id, name, location, category, subtype, source_confidence) values\n')
        values = []
        for gers, name, lat, lon, category, subtype, confidence in rows[start:start + BATCH]:
            values.append(
                f"({lit(gers)}, {lit(name)}, 'POINT({lon} {lat})', {lit(category)}, {lit(subtype)}, {lit(confidence)})"
            )
        out.write(',\n'.join(values))
        out.write('\non conflict (gers_id) do nothing;\n')
print(f'{len(rows)} NYC places -> supabase/seed.sql')
PYEOF
ls -lh supabase/seed.sql
