#!/bin/bash
# Generates supabase/seed.sql: the NYC subset of docs/private/places.sqlite as
# idempotent INSERTs into public.places (WKT for the geography column).
# Apply with: supabase db push --include-seed   (after supabase link)
# Gotcha: push only executes the seed on FIRST apply; after that it just
# re-tracks the file hash. To load newly added rows into a live DB, insert the
# delta via the REST API (ignore-duplicates upsert on gers_id) — see the
# session notes from 2026-08-29 — or wait for the planned upsert refresh script.
set -euo pipefail
cd "$(dirname "$0")/.."

python3 - <<'PYEOF'
import sqlite3

# NYC (five boroughs plus a NJ sliver) per roadmap item 4, plus the Bay Area
# (SF, Oakland/Berkeley, Lafayette, north peninsula) so the founder's own
# onboarding exercises the real detection path.
BOXES = [
    ((40.49, 40.92), (-74.27, -73.68)),   # NYC
    ((37.60, 37.95), (-122.55, -122.05)), # SF Bay
]
BATCH = 1000

db = sqlite3.connect('docs/private/places.sqlite')
rows = []
for (lat_min, lat_max), (lon_min, lon_max) in BOXES:
    rows += db.execute(
        'SELECT gers_id, name, lat, lon, category, subtype, confidence FROM places'
        ' WHERE lat BETWEEN ? AND ? AND lon BETWEEN ? AND ?',
        (lat_min, lat_max, lon_min, lon_max),
    ).fetchall()

def lit(value):
    if value is None:
        return 'null'
    if isinstance(value, str):
        return "'" + value.replace("'", "''") + "'"
    return repr(value)

with open('supabase/seed.sql', 'w') as out:
    out.write('-- Generated by scripts/seed-places-nyc.sh — do not edit.\n')
    for start in range(0, len(rows), BATCH):
        out.write('insert into places (gers_id, name, location, category, subtype, source_confidence) values\n')
        values = []
        for gers, name, lat, lon, category, subtype, confidence in rows[start:start + BATCH]:
            values.append(
                f"({lit(gers)}, {lit(name)}, 'POINT({lon} {lat})', {lit(category)}, {lit(subtype)}, {lit(confidence)})"
            )
        out.write(',\n'.join(values))
        out.write('\non conflict (gers_id) do nothing;\n')
print(f'{len(rows)} places (NYC + SF Bay) -> supabase/seed.sql')
PYEOF
ls -lh supabase/seed.sql
